version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing"
  pre_build:
    commands:
      - echo "Pre Build"
      - npm install
  build:
    commands:
      - echo "Build"
      - npm run build
      - echo "Completed Build project"
  post_build:
    commands:
      - aws s3 cp ./build/* s3://monish-cicd-demo/
      - echo "Ending..."

artifacts:
  files:
    - 'build/*'
    - 'build/**/*'
